spring:
  application:
    name: Grim
  datasource:
    url: jdbc:oracle:thin:@192.168.20.233:1521:xe
    username: GRIM
    password: GRIM
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:uploads/

server:
  port: 80

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: VARCHAR
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.grim.member.model.dto, com.grim.point.model.dto


servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB

logging:
  level:
    org.apache.ibatis: DEBUG
    java.sql: DEBUG
    jdbc.sqlonly: DEBUG
    jdbc.resultset: DEBUG
    jdbc.audit : DEBUG
 
jwt:
  secret: bnHco09AQp0817RoCFGV/cbXRIAqn+xzm3hikgBqm0A=